### PR TITLE
Fix "global" argument for Mac

### LINKED ISSUE #79: Error downloading "global" data with wdpa_fetch
Hi @jeffreyhanson 

Trying to download all the wdpa data with the "global" option and I get an error. Are you getting the same error?

I get the error whether I specific the `download_dir` or not.

``` r
wdpa_data <- wdpar::wdpa_fetch("global", wait = TRUE,
             download_dir = rappdirs::user_data_dir("wdpar"))
#> Warning in utils::unzip(x, exdir = tdir): error -1 in extracting from zip file
#> Error in wdpa_read(file_path, n): global data format not recognized.
```

<sup>Created on 2024-05-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by jaseeverett**
This seems to work on 2 x MBPs (M1Max and M2Pro)

Including the getOption seemed to solve the unzip issue. rappdirs returned a ~ for the home directory which then didn't work with the unzip, so I added a expand.path

closes #79

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
Thank you very much for the PR @jaseeverett! Just a quick question, why the need to set `utils::unzip(x, exdir = tdir, unzip = getOption("unzip"))`? Does the default "internal" for `unzip()` not work on macs?

**Comment by jaseeverett** [comment]
> Thank you very much for the PR @jaseeverett! Just a quick question, why the need to set `utils::unzip(x, exdir = tdir, unzip = getOption("unzip"))`? Does the default "internal" for `unzip()` not work on macs? Sorry just saw your edit to the post.

No worries. No it doesn't. That was the core issue. The file downloaded fine, but the error was the unzipping. There are numerous posts around the web about the M1/M2/M3 Macs not unzipping without the `getOption`. I don't know the underlying issue and why it is different to `internal`......

**Comment by jeffreyhanson** [comment]
Ah - interesting! Thanks for tracking that down

**Comment by jeffreyhanson** [comment]
@jaseeverett, I've just added a commit to your PR to help make it robust against a potentially argument to `download_dir` (e.g., in case a user accidently supplied a number, NULL, NA value, etc). Could you please check that have broken your patch on your mac computer?

File: R/wdpa_fetch.R [hunk 1]
```diff
@@ -157,17 +157,20 @@ wdpa_fetch <- function(x, wait = FALSE,
...
-  download_dir <- path.expand(download_dir) 
-  dir.create(download_dir, showWarnings = FALSE, recursive = TRUE)
   assertthat::assert_that(
     assertthat::is.string(x),
     assertthat::is.dir(download_dir),
     assertthat::is.flag(force_download),
     assertthat::is.flag(verbose),
     assertthat::is.flag(check_version),
     identical(x, "global") || assertthat::is.string(country_code(x)))
+  dir.create(download_dir, showWarnings = FALSE, recursive = TRUE)
```
Comment (jaseeverett) [inline R/wdpa_fetch.R:173]: The directory is not created until after the presence is tested `assertthat::is.dir(download_dir)`

Comment (jeffreyhanson) [reply R/wdpa_fetch.R:173]: Ah - thanks for catching that. I'll push another commit

**Comment by jeffreyhanson** [comment]
Ok - could you try again with the updated code?

**Comment by jaseeverett** [comment]
Works well now

**Comment by jeffreyhanson** [comment]
Awesome - thanks!
